name: Local Self-Hosted Deploy with Test

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: go test ./... -v

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Deploying App
        run: |
          cd ~/user/golang/go-devops-api
          git pull origin master
          docker compose up -d --build