name: Local Self-Hosted Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    # --- สำคัญมาก: เปลี่ยนจาก ubuntu-latest เป็น self-hosted ---
    runs-on: self-hosted
    # -------------------------------------------------------
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploying App
        run: |
          # เข้าไปที่โฟลเดอร์โปรเจกต์
          cd ~/user/golang/go-devops-api
          
          # ดึงโค้ดล่าสุด (เพราะเราใช้ self-hosted เครื่องนี้มี git อยู่แล้ว)
          git pull origin master
          
          # สั่ง Docker รันใหม่
          docker compose up -d --build
          
          # ล้าง Image เก่า
          docker image prune -f